#!/bin/bash

VERSION=4.1.2
PACKAGE=singularityce
TOOL=singularity
DIRECTORY=$(dirname $0)

STORAGES=(/ocean /local)

OPTIONS=""
for STORAGE in "${STORAGES[@]}"
do
  	if [ -d "$STORAGE" ]; then
		OPTIONS=$OPTIONS" -B $STORAGE"
        fi
done

if id | grep -q hubmap && [ -d "/hive" ]; then
	OPTIONS=$OPTIONS" -B /hive"
fi

if id | grep -q bil && [ -d "/bil" ]; then
	OPTIONS=$OPTIONS" -B /bil"
fi

apptainer exec $OPTIONS $DIRECTORY/apptainer-$PACKAGE-$VERSION.sif $TOOL "$@"
